### ISSUE TITLE
Add sample regos from blog post to this repo

### ISSUE THREAD

**Issue by rbkaspr** [instrumenta/helm-conftest#2]
I'm having issues with the policy examples in your blog post https://garethr.dev/2019/08/using-conftest-and-kubeval-with-helm/, namely I get segfaults whenever I try to update using the example conftest.toml.

Would it be possible to either add the example policy regos to this repo, or else can you tell my why I may be seeing the issues I'm seeing?

**Comment by rbkaspr** [comment]
Using plugin version 0.15.0 and Helm 3.1.1

**Comment by agilgur5** [comment]
I think you can find all the policies in the `policies` repo, which is meant to be generic to where it's used (`opa`, `conftest`, `helm conftest` etc): https://github.com/instrumenta/policies
